steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -f catalogue/Dockerfile -t northamerica-south1-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/craftista:tag1 .
  automapSubstitutions: true
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'northamerica-south1-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/craftista:tag1'