steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    cd catalogue
    docker build \
      -t ${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA \
      -t ${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BRANCH_NAME \
      .
  automapSubstitutions: true
- id: 'Push'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BRANCH_NAME'

- id: 'Deploy'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}' # e.g., myapp-develop, myapp-qa, myapp-main
    - '--image'
    - '${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BRANCH_NAME'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- '${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
- '${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BRANCH_NAME'


substitutions:
  _REGION: northamerica-south1
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_REPO_LOCATION: northamerica-south1
  _LOG_LEVEL: debug
  _SERVICE_NAME: craftista